name: Build MyOS

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm qemu gcc-multilib
        
    - name: Build
      run: |
        make
        
    - name: Run in QEMU (test)
      run: |
        make run